version: "3.9"
services:
  web:
    build: ./Cliente
    ports:
      - "8000:5000"
    depends_on:
      - redis
      - server
      - postgres
  redis:
    build: "./Redis"
    ports: 
      - "6379:6379"
  server:
    build: ./Servidor
    depends_on:
      - postgres
  postgres:
    build: ./Postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=Tarea1
      - ALLOW_EMPTY_PASSWORD=yes


